---
title: dart.tools
author: Nikolai Simonov
email: nickolay.simonov@outlook.com
description: Dart tools. personal projekt
baseurl: "/"
url: https://dart.tools/
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus

# Google services
google_analytics: UA-165580497-1
